export const fields = [
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},
    {title:'Blockchain Engineers',style:{}},
    {title:'Frontend Engineers',style:{}},


]